rm -rf BAM/
rm -rf benchmark/
rm -rf FASTQ/CONCATENATED/
rm -rf FASTQ/Hairpin/
rm -rf FASTQ/Mature/
rm -rf FASTQ/PhiX/
rm -rf FASTQ/Reference/
rm -rf FASTQ/TRIMMED/
rm -rf FASTQ/tRNA/
rm -rf QC/
rm -rf QUANTIFICATION/
rm -rf STAR_tmp/
rm -rf STATS/
rm -rf .snakemake