# absolute path to the project folder
project-folder: "/scratch/project_2001310/BovReg_TwinBullSperm-orig"
pipeline-folder: "/scratch/project_2001310/Snakebite-miRNA"
scratch-folder: $LOCAL_SCRATCH
rawdata-folder: "FASTQ/RAW"
pipeline-config: "Snakebite-miRNA_config.yaml"
server-config: "Snakebite-miRNA_server-config.yaml"
samplesheet-file: "samplesheet.tsv"
sampleInfo-file: "sampleInfo.tsv"

tRNARef: "References/tRNA/bosTau8-tRNAs.fa"
phixRef: "References/phix/phix174.fa"
matureRef: "References/mature.fa"
hairpinRef: "References/hairpin.fa"
reference: "References/ARS12/Bos_taurus.ARS-UCD1.2.dna.primary_assembly.fa"
refAnnot: "References/ARS12/Bos_taurus.ARS-UCD1.2.95.gtf"
starbase: "References/STAR"

params:
  protocol: "" # Use settings for "illumina" "nextflex" or "qiagen". Keep empty for own protocol (then cutadapt needss to be configured!)
  species-id: "bta"  # used to filter mature.fa and hairpin.fa, check for required identifier.
  bowtie:
    m: 1
    mMulti: 5
    k: 1
    threads: 20
  star:
    limitBAMsortRAM: "1436064474"
  cutadapt:
    adapter3p: ""
    adapter5p: ""
    minLength: 16
    qualtrim: 30
    fiveprimetrim: 0
    threeprimetrim: 0
  fastx:
    length: 20
  extractSoftClipped:
    length: 15
  stringtie:
    tpm: 0
  novel:
    minCover: 10
  de:
    minAbundance: 10
    FDR: 0.1