# absolute path to the project folder
project-folder: /scratch/project_2001310/BovReg_TwinBullSperm-orig
pipeline-folder: /scratch/project_2001310/Pipeline-miRNA
scratch-folder: $LOCAL_SCRATCH
rawdata-folder: /scratch/project_2001310/BovReg_TwinBullSperm-orig/FASTQ/RAW
pipeline-config: /scratch/project_2001746/TestProject/GBS-pipeline_config.yaml
server-config: /users/fischerd/git/Pipeline-miRNA/miRNA-pipeline_puhti-config.yaml
samplesheet-file: /scratch/project_2001310/BovReg_TwinBullSperm-orig/samplesheet.tsv

tRNARef: /scratch/project_2001310/BovReg_TwinBullSperm-orig/References/tRNA/bosTau8-tRNAs.fa
phixRef: /scratch/project_2001310/BovReg_TwinBullSperm-orig/References/phix/phix174.fa
matureRef: /scratch/project_2001310/BovReg_TwinBullSperm-orig/References/mature.fa
hairpinRef: /scratch/project_2001310/BovReg_TwinBullSperm-orig/References/hairpin.fa
reference: /scratch/project_2001310/BovReg_TwinBullSperm-orig/References/ARS12/Bos_taurus.ARS-UCD1.2.dna.primary_assembly.fa
refAnnot: /scratch/project_2001310/BovReg_TwinBullSperm-orig/References/ARS12/Bos_taurus.ARS-UCD1.2.95.gtf
starbase: /scratch/project_2001310/BovReg_TwinBullSperm-orig/References/STAR

params:
  protocol: "qiagen" # Use settings for "illumina" "nextflex" or "qiagen". Keep empty for own protocol (then cutadapt needss to be configured!)
  species-id: "bta"  # used to filter mature.fa and hairpin.fa, check for required identifier.
  bowtie:
    m: 1
    mMulti: 5
    k: 1
    threads: 20
  cutadapt:
    adapter: "AACTGTAGGCACCATCAAT"
    minLength: 16
    qualtrim: 30
    fiveprimetrim: 0
    threeprimetrim: 0
  fastx:
    length: 20
  extractSoftClipped:
    length: 15
  stringtie:
    tpm: 0
