##### Singularity container #####
---
bedtools: "docker://fischuu/bedtools:2.30-0.1"
bowtie: "docker://fischuu/bowtie:1.2.2-0.3"
cutadapt: "docker://fischuu/cutadapt:2.8-0.3"
fastqc: "docker://fischuu/gbs:0.2"
helpers: "docker://fischuu/hrp_helpers:0.1"
multiqc: "docker://fischuu/gbs:0.2"
reads: "docker://fischuu/hrp_reads:0.2"
samtools: "docker://fischuu/samtools:1.9-0.2"
star: "docker://fischuu/star:2.7.3a-0.2"
subread: "docker://fischuu/subread:2.0.1-0.1"
seqkit: "docker://fischuu/seqkit:2.1.0-0.2"
reporting: "docker://fischuu/r-gbs:4.1.2-0.4"
stringtie: "docker://fischuu/stringtie:2.2.1-0.1"