# Paths and parameters relative to references
---
references:
  trnaref: "references/bosTau9-mature-tRNAs.fa"
  phixref: "references/phix.fa"
  matureref: "references/mature.fa"
  hairpinref: "references/hairpin.fa"
  otherRef: ""
  reference: "references/ARS12/Bos_taurus.ARS-UCD1.2.dna.primary_assembly.fa"
  refAnnot: "References/ARS12/Bos_taurus.ARS-UCD1.2.95.gtf"
  starbase: "References/STAR"